CREATE PROCEDURE FI_SP_IncBeneficiarioV1
    @NOME          VARCHAR (250),
    @CPF           VARCHAR (15),
    @IDCLIENTE     bigint
AS
BEGIN
	INSERT INTO BENEFICIARIOS (NOME, CPF, IDCLIENTE ) 
	VALUES (@NOME, @CPF, @IDCLIENTE)

	SELECT SCOPE_IDENTITY()
END

--DROP PROCEDURE [FI_SP_IncBeneficiarioV1];  
--GO  